// <auto-generated />
using System;
using GGWalks.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GGWalks.API.Migrations
{
    [DbContext(typeof(GGWalksDBContext))]
    [Migration("20260925192404_Seeding data to difficulties and migration")]
    partial class Seedingdatatodifficultiesandmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GGWalks.API.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f11e1ef8-bf11-4b54-b083-66d9c7ed096a"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("9ae1daa7-4787-408e-9f80-eba016fced94"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("5c0fa415-0c68-43f2-8ad6-32388a9ca610"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("GGWalks.API.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4e87bdce-b9a7-4506-aaf2-15dc1e892cfd"),
                            Code = "CC",
                            Name = "Cyber City",
                            RegionImageUrl = "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0f/b8/e2/a4/photo5jpg.jpg?w=1600&h=-1&s=1"
                        },
                        new
                        {
                            Id = new Guid("2539941c-7c1e-4110-93e3-486dac8394b7"),
                            Code = "UV",
                            Name = "Udyog Vihar"
                        },
                        new
                        {
                            Id = new Guid("52f96bc5-87e0-44c2-bc09-fb704b97292b"),
                            Code = "PV",
                            Name = "Palam vihar"
                        },
                        new
                        {
                            Id = new Guid("38f20107-91b9-42ec-a49a-7d46b39f693c"),
                            Code = "CH",
                            Name = "Cyber Hub",
                            RegionImageUrl = "https://b.zmtcdn.com/data/pictures/2/18289242/2fd5c943d0a52b9ebcbb50c674b8ca8c.jpg?w=1600&h=-1&s=1"
                        });
                });

            modelBuilder.Entity("GGWalks.API.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("GGWalks.API.Models.Domain.Walk", b =>
                {
                    b.HasOne("GGWalks.API.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GGWalks.API.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
